#ifndef GAMEINFO_H
#define GAMEINFO_H
#pragma once
#include "process_op.h"

int GetGameUI();
int GetGameMode();
int GetScene();
int GetRowCount();
bool CheckBoardOn();
bool CheckGameOn();
void Resumemower();
void Startmower(int);
void Clearmower(int);
void SetGamePause();
void PlantNoLimit(bool);
void LockShovel(bool);
void PlantInvincible(bool);
void UnlockAllMode(bool);
void UnlockGoldFlower(bool);
void PassGame();
void HideShovel(bool);
void HideMenu(bool);
void SetNoSun(bool);
void AutoCollect(bool);
void ZombieInvincible(bool);
void MushroomNoSleep(bool);
void StopZombieMove(bool);
void StopSystemZombie(bool);
void NoCrater(bool);
void AllowBackRunning(bool);
void PlaceNoCD(bool);
void IgnoreSun(bool);
void PurpleSeedUnlimited(bool);
#endif // GAMEINFO_H
